"use client";

import React, {
  createContext,
  useContext,
  useState,
  ReactNode,
  useEffect,
} from "react";
import { Language } from "@/types";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

const translations = {
  tr: {
    title: "Read Circle",
    subtitle: "Kaynak Dağıtım Platformu",
    backHome: "Ana Sayfa",
    loginButton: "GİRİŞ YAP",
    logoutButton: "Çıkış Yap",
    guestRegister: "Kayıt Ol",
    welcome: "Merhaba",
    menuLanguage: "Dil Ayarları",
    footerDesc: "Manevi birliktelik ve kaynak dağıtım platformu.",
    rightsReserved: "Tüm hakları saklıdır.",
    allahAccept: "Allah kabul etsin.",
    adminButton: "Admin olarak giriş yap!",
    loading: "Yükleniyor...",
    adminTitle: "Yönetim Paneli",
    distributedResources: "Bölüştürülecek Kaynaklar",
    individualResources: "Bireysel Kaynaklar",
    setTargetCounts: "Hedef Sayıları Belirle (Opsiyonel)",
    default: "Varsayılan",
    participantCount: "Kaç Kişi Okuyacak?",
    createDistribution: "DAĞITIMI OLUŞTUR",
    linkCreated: "Link Oluşturuldu:",
    copy: "Kopyala",
    delete: "Sil",
    dashboard: "Panel",

    landingHeroTitle: "Manevi Birliktelik",
    platform: "Platformu",
    landingHeroSubtitle:
      "Kuran hatimleri, Cevşen halkaları ve zikir programlarınızı kolayca organize edin. Sevdiklerinizle birlikte manevi hedeflerinize ulaşın.",
    getStarted: "Hemen Başla",
    sessionCodePlaceholder: "Halka Kodu",
    join: "Katıl",
    guestNote: "Kayıt olmadan misafir olarak da katılabilirsiniz.",

    featuresTitle1: "Kuran & Cevşen Hatimleri",
    featuresDesc1:
      "Cüzleri veya sayfaları otomatik dağıtın. Kimin nerede kaldığını canlı takip edin.",
    featuresTitle2: "Ortak Zikir Halkaları",
    featuresDesc2:
      "Salavat, dua ve zikir gibi hayırlarda ortak havuza katkıda bulunun.",
    featuresTitle3: "Mobil Uyumlu Okuma",
    featuresDesc3:
      "Uygulama içinden ayrılmadan Kuran sayfalarını, Cevşen bablarını veya zikirleri okuyun.",

    howItWorksTitle: "Nasıl Çalışır?",
    step1Title: "Oturum Oluştur",
    step1Desc: "Okunacak kaynağı (Yasin, Hatim vb.) ve kişi sayısını belirle.",
    step2Title: "Davet Et",
    step2Desc: "Oluşan kısa kodu veya linki sevdiklerinle paylaş.",
    step3Title: "Tamamla",
    step3Desc: "Herkes kendi parçasını alıp okusun, ilerlemeyi anlık gör.",

    joinTitle: "Halkaya Katıl",
    joinIntro: "Lütfen adınızı giriniz (Misafir)",
    yourName: "Adınız",
    takeRead: "AL",
    readText: "Oku",
    completed: "Tamamlandı",
    cancel: "İptal",
    page: "Sayfa",
    previous: "Önceki",
    next: "Sonraki",
    participantName: "Katılımcı Adı",
    confirmDeleteSession:
      "Bu oturumu tamamen silmek istediğinize emin misiniz? Tüm veriler kaybolacak.",
    confirmLeaveSession:
      "Bu halkadan ayrılmak üzeresiniz. Aldığınız tüm görevler iptal edilecek.",
    confirmResetSession:
      "Bu dağıtımı sıfırlamak istediğinize emin misiniz? Tüm katılımcılar çıkarılacak ve okumalar sıfırlanacak.",
    resetSuccess: "Oturum başarıyla sıfırlandı! Yeni katılımcılar bekleniyor.",
    resetFailPrefix: "Sıfırlama başarısız: ",
    deleteSuccess: "Oturum başarıyla silindi.",
    deleteFail: "Silme işlemi başarısız oldu.",
    leaveSuccess: "Halkadan ayrıldınız.",
    leaveFail: "Ayrılma işlemi başarısız oldu.",
    reset: "Sıfırla / Yeniden Başlat",
    leave: "Ayrıl",
    errorOccurred: "Hata oluştu.",
    confirmDelete: "Silmek istediğinize emin misiniz?",
    deletedSuccess: "Dağıtım silindi.",
    distCode: "Kod",
    finished: "Tamamladıysan tikla",
    confirmComplete: "Bu parçayı okuduğunuzu onaylıyor musunuz?",
    confirmCancel: "Bu parçayı okumaktan vazgeçmek istiyor musunuz?",
    cancelFailed: "İptal edilemedi.",
    connectionError: "Bağlantı hatası.",
    errorFetchFailed: "Veri alınamadı. Hata Kodu:",
    unexpectedError: "Beklenmedik bir hata oluştu.",
    readingTitle: "Okuma",
    closeWindow: "Pencereyi Kapat",
    close: "Kapat",
    chapter: "BAB",
    group: "Grup",
    translationTitle: "Türkçe Meali",
    translationPending: "Çeviri hazırlanıyor...",
    arabicPage: "Arapça Sayfa",
    meaningPage: "Meal Sayfa",
    otherResource: "Diğer",
    alertSelectResource: "Lütfen en az bir kaynak seçiniz.",
    confirmReset:
      "Tüm veritabanı sıfırlanıp varsayılan veriler yüklenecek. Emin misiniz?",
    refresh: "Verileri Yükle / Sıfırla",
    enterCode: "Dağıtım Kodunu Giriniz",
    joinButton: "Katıl",
    remaining: "Kalan",
    tabArabic: "Arapça",
    tabLatin: "Okunuş",
    tabMeaning: "Meal",
    successReset: "Sıfırlandı!",
    successDelete: "Silindi!",
    clickToCount: "OKUDUKÇA TIKLAYINIZ",
    person: "Kişi",
    part: "Parça",
    target: "Hedef",
    total: "Toplam",
    pieces: "Adet",
    myCreatedTitle: "Yönettiğim Dağıtımlar",
    noCreatedYet: "Henüz bir dağıtım başlatmadın.",
    trackButton: "Takip Et",
    selectAndRead: "SEÇ & OKU",
    full: "DOLU",
    alertEnterName: "Lütfen önce yukarıya isminizi yazın.",
    alertStatus: "Durum: ",
    alertTakenSuccess: "Harika! Bu bölümü okumayı üstlendiniz.",
    alertErrorPrefix: "Hata: ",
    errorInvalidCode: "Hata: Geçersiz kod veya sunucu kapalı.",
    decrease: "AZALT",
    errorAlreadyTaken: "Bu parça maalesef başkası tarafından alınmış.",
    registerTitle: "Hesap Oluştur",
    registerSubtitle: "Aramıza katılmak için bilgilerinizi girin",
    usernameLabel: "Kullanıcı Adı",
    passwordLabel: "Şifre",
    placeholderUserExample: "Örn: ahmet123",
    placeholderPass: "******",
    registerButton: "KAYIT OL",
    registering: "Kaydediliyor...",
    haveAccount: "Zaten hesabınız var mı?",
    loginLink: "Giriş Yap",
    registerSuccess: "Kayıt Başarılı! Giriş yapabilirsiniz.",
    errorPrefix: "Hata: ",
    monitorTitle: "Dağıtım Takibi",
    monitorSubtitle: "Bir kod girerek kimin ne aldığını kontrol edin.",
    statusEmpty: "BOŞTA",
    statusTaken: "ALINDI",
    assignedTo: "Alan Kişi",
    resource: "Kaynak / Parça",
    progress: "İlerleme / Hedef",
    backToAdmin: "Admin Paneline Dön",
    occupancy: "DOLULUK",
    statusHeader: "Durum",
    targetLabel: "HEDEF",
    select: "SEÇ",
    cancelRead: "Okumaktan Vazgeç",
    createDistTitle: "Yeni Dağıtım Başlat",
    createDistDesc: "Hatim, Yasin veya Zikir halkası oluşturup linki paylaş.",
    joinDistTitle: "Bir Halkaya Katıl",
    joinDistDesc: "Sana gönderilen kodu aşağıya girerek dahil ol.",
    createButton: "OLUŞTUR",
    enterCodePlaceholder: "Dağıtım Kodu (Örn: 12345)",
    joinInputPlaceholder: "Dağıtım Kodu (Örn: 12345)",
    guestLogin: "Giris Yap",
    imageMode: "Resim Modu",
    loginRequiredMsg: "Parça seçmek için giriş yapmalısınız.",
    loginOrRegister: "Giriş Yap veya Kayıt Ol",
    guestSubtitle: "Manevi birliktelik platformu",
    guestMessage:
      "Halkalara katılmak veya kendi dağıtımını oluşturmak için lütfen giriş yap.",
    guestCheckCode: "Sadece bir koda bakmak mı istiyorsun?",
    guestCodePlaceholder: "Kod giriniz",
    appTitle: "Read Circle",
    loginTitle: "Giriş Yap",
    noAccount: "Hesabın yok mu?",
    registerLink: "Hemen Kayıt Ol",
    loginError: "Kullanıcı adı veya şifre hatalı",
    myCirclesTitle: "Katıldığım Halkalar",
    noCirclesYet: "Henüz bir halkaya katılmadın.",
    continueButton: "DEVAM ET",
    placeholderUser: "Kullanıcı adınız",
    creatorLabel: "Kurucu",
  },
  ku: {
    title: "Read Circle",
    appTitle: "Read Circle",
    subtitle: "Platforma Belavkirina Çavkaniyan",
    backHome: "Mal",
    loginButton: "TÊKETIN",
    dashboard: "Panel",

    landingHeroTitle: "Yekîtiya Manewî",
    platform: "Platforma",
    landingHeroSubtitle:
      "Xatimên Quranê, xelekên Cewşenê û bernameyên zikran bi hêsanî organîze bikin",
    getStarted: "Dest Pê Bike",
    sessionCodePlaceholder: "Koda Xelekê",
    join: "Tevlî Bibe",
    guestNote: "Hûn dikarin bêyî qeydkirinê wekî mêvan tevlî bibin.",

    featuresTitle1: "Xatimên Quran & Cewşenê",
    featuresDesc1:
      "Cuz an rûpelan bixweber belav bikin. Zindî bişopînin kî li ku maye.",
    featuresTitle2: "Xelekên Zikrê Yên Hevpar",
    featuresDesc2:
      "Di zikran de mîna Selewat û duayan beşdarî hewza hevpar bibin.",
    featuresTitle3: "Xwendina Li Gorî Mobîlê",
    featuresDesc3:
      "Bêyî ku ji sepanê derkevin rûpelên Quranê an beşên Cewşenê bixwînin.",

    howItWorksTitle: "Çawa Dixebite?",
    step1Title: "Rûniştinê Ava Bike",
    step1Desc: "Çavkaniyê (Yasîn, Xatim hwd.) û hejmara kesan diyar bike.",
    step2Title: "Dawet Bike",
    step2Desc: "Koda kurt an lînka hatî çêkirin parve bike.",
    step3Title: "Temam Bike",
    step3Desc: "Her kes para xwe bixwîne, pêşveçûnê di cih de bibîne.",
    welcome: "Bi xêr hatî,",
    dashboardIntro: "Îro di rêwîtiya xwe ya manewî de dixwazî çi bikî?",
    createNewSession: "Xeleka Nû Ava Bike",
    managedSessions: "Xelekên Ez Birêve Dibim",
    joinedSessions: "Xelekên Ez Tevlî Bûme",
    noSessionYet: "Hîn tune.",
    create: "Ava Bike",
    codePlaceholder: "Kod...",

    joinTitle: "Tevlî Xelekê Bibe",
    joinIntro: "Navê xwe binivîse (Mêvan)",
    yourName: "Navê Te",
    distributedResources: "Çavkaniyên Hatin Belavkirin",
    individualResources: "Çavkaniyên Bireysel",
    takeRead: "BIGIRE",
    readText: "Bixwîne",
    completed: "Temam Bû",
    cancel: "Betal Bike",
    page: "Rûpel",
    previous: "Pêş",
    next: "Paş",
    logoutButton: "Derketin",
    guestRegister: "Qeyd Bibe",
    menuLanguage: "Mîhengên Ziman",
    footerDesc: "Platforma yekîtiya manewî û belavkirina çavkaniyan.",
    rightsReserved: "Hemû maf parastî ne.",
    allahAccept: "Xwedê qebûl bike.",
    adminButton: "Wekî Admin têkeve!",
    loading: "Tê barkirin...",
    adminTitle: "Panela Rêveberiyê",
    setTargetCounts: "Hejmarên Hedef Diyar Bike (Vebijarkî)",
    default: "Pêşwext",
    participantCount: "Çend Kes Wê Bixwînin?",
    createDistribution: "BELAVKIRINÊ PÊK BÎNE",
    linkCreated: "Lînk Hat Çêkirin:",
    copy: "Kopyake",
    alertSelectResource: "Ji kerema xwe qet nebe çavkaniyek hilbijêrin.",
    confirmReset:
      "Hemû databas wê were sifirkirin û daneyên pêşwext werin barkirin. Tu piştrast î?",
    errorOccurred: "Xetayek çêbû.",
    confirmDeleteSession:
      "Tu piştrast î ku dixwazî vê xelekê bi temamî jê bibî? Hemû dane wê winda bibin.",
    confirmLeaveSession:
      "Tu li ber î ku ji vê xelekê derkevî. Hemû parçeyên te wê werin betalkirin.",
    confirmResetSession:
      "Tu piştrast î ku dixwazî vê xelekê sifir bikî? Hemû beşdar wê werin derxistin û xwendin wê werin sifirkirin.",
    resetSuccess: "Xelek bi serkeftî hate sifirkirin! Li benda beşdarên nû ye.",
    resetFailPrefix: "Sifirkirin bi ser neket: ",
    deleteSuccess: "Xelek bi serkeftî hate jêbirin.",
    deleteFail: "Jêbirin bi ser neket.",
    leaveSuccess: "Tu ji xelekê derketî.",
    leaveFail: "Derketina ji xelekê bi ser neket.",
    reset: "Sifir Bike / Nû Bike",
    delete: "Jê Bibe",
    leave: "Derkeve",
    refresh: "Daneyan Bar Bike / Sifir Bike",
    enterCode: "Koda Belavkirinê Binivîse",
    joinButton: "Tevlî Bibe",
    finished: "Heke te xelas kir, bitikîne",
    guestLogin: "Bikevê",
    remaining: "Mayî",
    tabArabic: "Erebî",
    tabLatin: "Bilêvkirin",
    tabMeaning: "Wate",
    successReset: "Hat Sifirkirin!",
    successDelete: "Hat Jêbirin!",
    clickToCount: "HER KU TE XWEND BITIKÎNE",
    person: "Kes",
    distCode: "Kod",
    confirmComplete: "Tu piştrast î ku te ev beş xwendiye?",
    confirmCancel: "Tu dixwazî dev ji xwendina vê beşê berdî?",
    cancelFailed: "Betalkirin biser neket.",
    connectionError: "Xetaya girêdanê.",
    errorFetchFailed: "Dâne nehatin standin. Koda Xetayê:",
    unexpectedError: "Xetayek neçaverêkirî çêbû.",
    readingTitle: "Xwendin",
    closeWindow: "Pencereyê Bigire",
    close: "Bigire",
    chapter: "BEŞ",
    group: "Kom",
    translationTitle: "Wateya Kurdî",
    translationPending: "Wergêr tê amadekirin...",
    arabicPage: "Rûpela Erebî",
    meaningPage: "Rûpela Wateyê",
    otherResource: "Yên din",
    part: "Parçe",
    target: "Hedef",
    total: "Giştî",
    pieces: "Heb",
    myCreatedTitle: "Belavkirinên Min ên Rêvebir",
    noCreatedYet: "Hêj te belavkirinek neda destpêkirin.",
    trackButton: "Bişopîne",
    selectAndRead: "HILBIJÊRE & BIXWÎNE",
    full: "TIJE",
    alertEnterName: "Ji kerema xwe pêşî navê xwe li jor binivîse.",
    alertStatus: "Rewş: ",
    alertTakenSuccess: "Gelek baş e! Te ev beş girt ser xwe.",
    alertErrorPrefix: "Xeta: ",
    errorInvalidCode: "Xeta: Kod nederbasdar e an server girtî ye.",
    decrease: "KÊM BIKE",
    errorAlreadyTaken:
      "Mixabin, ev parçe ji aliyê kesekî din ve hatiye girtin.",
    registerTitle: "Hesab Çêbike",
    registerSubtitle: "Ji bo tevlî me bibî agahiyên xwe binivîse",
    usernameLabel: "Navê Bikarhêner",
    passwordLabel: "Şîfre",
    placeholderUserExample: "Mînak: azad123",
    placeholderPass: "******",
    registerButton: "QEYD Bûyîn",
    registering: "Tê qeydkirin...",
    haveAccount: "Ma hesabê te heye?",
    loginLink: "Têkeve",
    registerSuccess: "Qeyd serkeftî bû! Niha dikarî têkevî.",
    errorPrefix: "Xeta: ",
    monitorTitle: "Şopandina Belavkirinê",
    monitorSubtitle: "Bi nivîsandina kodê kontrol bike ka kî çi girtiye.",
    statusEmpty: "VALA",
    statusTaken: "HAT GIRTIN",
    assignedTo: "Kesê Girtiye",
    resource: "Çavkanî / Parçe",
    progress: "Pêşveçûn / Hedef",
    backToAdmin: "Vegere Panela Admin",
    occupancy: "TIJEBÛN",
    statusHeader: "Rewş",
    targetLabel: "HEDEF",
    select: "HILBIJÊRE",
    cancelRead: "Xwendinê Betal Bike",
    createDistTitle: "Xeleka Nû Destpê Bike",
    createDistDesc: "Xeleka Hatim, Yasîn an Zikirê çêbike û lînkê parve bike.",
    joinDistTitle: "Tevlî Xelekê Bibe",
    joinDistDesc:
      "Koda ku ji te re hatiye şandin li jêr binivîse û beşdar bibe.",
    createButton: "PÊK BÎNE",
    enterCodePlaceholder: "Koda Belavkirinê (Mînak: 12345)",
    joinInputPlaceholder: "Koda Belavkirinê (Mînak: 12345)",
    participantName: "Navê Beşdar",
    imageMode: "Moda Wêneyê",
    loginRequiredMsg: "Ji bo hilbijartina parçeyekê divê têkevî.",
    loginOrRegister: "Têkeve an Qeyd Bibe",
    guestSubtitle: "Platforma yekîtiya manewî",
    guestMessage:
      "Ji bo tevlî xelekan bibî an belavkirina xwe çêbikî ji kerema xwe têkeve.",
    guestCheckCode: "Tenê dixwazî li kodekê binêrî?",
    guestCodePlaceholder: "Kod binivîse",
    loginTitle: "Têkeve",
    noAccount: "Ma hesabê te tune?",
    registerLink: "Hemen Qeyd Bibe",
    loginError: "Navê bikarhêner an şîfre şaş e",
    myCirclesTitle: "Xelekên Ez Tevlî Bûm",
    noCirclesYet: "Hêj tevlî tu xelekê nebûyî.",
    continueButton: "DEWAM BIKE",
    placeholderUser: "Navê te yê bikarhêner",
    creatorLabel: "Avaker",
  },
  en: {
    title: "Read Circle",
    subtitle: "Resource Distribution Platform",
    backHome: "Home",
    loginButton: "LOGIN",
    logoutButton: "Logout",
    guestRegister: "Register",
    welcome: "Welcome",
    dashboard: "Dashboard",

    landingHeroTitle: "Spiritual Union",
    platform: "Platform",
    landingHeroSubtitle:
      "Easily organize Quran khatms, Cevshen circles, and dhikr programs. Achieve your spiritual goals with your loved ones.",
    getStarted: "Get Started",
    sessionCodePlaceholder: "Session Code",
    join: "Join",
    guestNote: "You can also join as a guest without registering.",

    featuresTitle1: "Quran & Cevshen Khatms",
    featuresDesc1:
      "Distribute juz or pages automatically. Track who is where in real-time.",
    featuresTitle2: "Joint Dhikr Circles",
    featuresDesc2:
      "Contribute to the common pool in dhikrs like Salawat and prayers.",
    featuresTitle3: "Mobile Friendly Reading",
    featuresDesc3:
      "Read Quran pages or Cevshen sections without leaving the app.",

    howItWorksTitle: "How It Works?",
    step1Title: "Create Session",
    step1Desc: "Select the resource (Yasin, Khatm, etc.) and number of people.",
    step2Title: "Invite",
    step2Desc: "Share the generated short code or link.",
    step3Title: "Complete",
    step3Desc: "Everyone reads their part, see progress instantly.",

    dashboardIntro:
      "What would you like to do on your spiritual journey today?",
    createNewSession: "Create New Circle",
    managedSessions: "Managed Circles",
    joinedSessions: "Joined Circles",
    noSessionYet: "None yet.",
    create: "Create",
    codePlaceholder: "Code...",
    joinTitle: "Join Circle",
    joinIntro: "Please enter your name (Guest)",
    yourName: "Your Name",
    distributedResources: "Shared Resources",
    individualResources: "Individual Resources",
    takeRead: "TAKE",
    readText: "Read",
    completed: "Completed",
    cancel: "Cancel",
    page: "Page",
    previous: "Previous",
    next: "Next",
    confirmComplete: "Do you confirm that you have read this part?",
    confirmCancel: "Do you want to cancel reading this part?",
    cancelFailed: "Could not cancel.",
    connectionError: "Connection error.",
    errorFetchFailed: "Failed to fetch data. Error Code:",
    unexpectedError: "An unexpected error occurred.",
    readingTitle: "Reading",
    closeWindow: "Close Window",
    close: "Close",
    chapter: "Chapter",
    group: "Group",
    translationTitle: "Translation",
    translationPending: "Translation pending...",
    arabicPage: "Arabic Page",
    meaningPage: "Meaning Page",
    otherResource: "Other",
    confirmDeleteSession:
      "Are you sure you want to delete this session permanently? All data will be lost.",
    confirmLeaveSession:
      "You are about to leave this circle. All your assignments will be cancelled.",
    confirmResetSession:
      "Are you sure you want to reset this distribution? All participants will be removed and readings reset.",
    resetSuccess: "Session successfully reset! Waiting for new participants.",
    resetFailPrefix: "Reset failed: ",
    deleteSuccess: "Session successfully deleted.",
    deleteFail: "Deletion failed.",
    leaveSuccess: "You have left the circle.",
    leaveFail: "Failed to leave the circle.",
    reset: "Reset / Restart",
    leave: "Leave",
    errorOccurred: "An error occurred.",
    menuLanguage: "Language Settings",
    footerDesc: "Spiritual connection and resource distribution platform.",
    rightsReserved: "All rights reserved.",
    allahAccept: "May Allah accept it.",
    adminButton: "Login as Admin!",
    loading: "Loading...",
    delete: "Jê bibe",
    confirmDelete: "Tu piştrast î ku dixwazî vê belavkirinê jê bibî?",
    deletedSuccess: "Belavkirin hat jêbirin.",
    adminTitle: "Admin Dashboard",
    setTargetCounts: "Set Target Counts (Optional)",
    default: "Default",
    participantCount: "Number of Participants?",
    createDistribution: "CREATE DISTRIBUTION",
    linkCreated: "Link Created:",
    copy: "Copy",
    alertSelectResource: "Please select at least one resource.",
    confirmReset: "Database will be reset to default data. Are you sure?",
    refresh: "Load / Reset Data",
    enterCode: "Enter Distribution Code",
    joinButton: "Join",
    remaining: "Remaining",
    tabArabic: "Arabic",
    tabLatin: "Transliteration",
    tabMeaning: "Translation",
    successReset: "Reset successful!",
    successDelete: "Deleted!",
    clickToCount: "CLICK AS YOU READ",
    person: "Person",
    part: "Part",
    target: "Target",
    total: "Total",
    pieces: "Pieces",
    myCreatedTitle: "My Distributions",
    noCreatedYet: "You haven't started any distribution yet.",
    trackButton: "Show Status",
    selectAndRead: "SELECT & READ",
    full: "TAKEN",
    alertEnterName: "Please enter your name above first.",
    alertStatus: "Status: ",
    alertTakenSuccess: "Great! You have successfully taken this part.",
    alertErrorPrefix: "Error: ",
    errorInvalidCode: "Error: Invalid code or server is down.",
    decrease: "DECREASE",
    errorAlreadyTaken:
      "Unfortunately, this part has already been taken by someone else.",
    registerTitle: "Create Account",
    finished: "If you finished, click",
    registerSubtitle: "Enter your details to join us",
    usernameLabel: "Username",
    passwordLabel: "Password",
    placeholderUserExample: "e.g. john123",
    placeholderPass: "******",
    registerButton: "REGISTER",
    registering: "Registering...",
    haveAccount: "Already have an account?",
    loginLink: "Login",
    registerSuccess: "Registration successful! You can login now.",
    errorPrefix: "Error: ",
    monitorTitle: "Distribution Monitor",
    monitorSubtitle: "Enter a code to check who took what.",
    statusEmpty: "AVAILABLE",
    statusTaken: "TAKEN",
    assignedTo: "Assigned To",
    resource: "Resource / Part",
    progress: "Progress / Target",
    backToAdmin: "Back to Dashboard",
    occupancy: "OCCUPANCY",
    statusHeader: "Status",
    targetLabel: "TARGET",
    select: "SELECT",
    cancelRead: "Cancel Reading",
    createDistTitle: "Start New Circle",
    createDistDesc:
      "Create a Quran, Yasin, or Dhikr circle and share the link.",
    joinDistTitle: "Join a Circle",
    joinDistDesc: "Enter the code shared with you to participate.",
    createButton: "CREATE",
    enterCodePlaceholder: "Distribution Code (e.g. 12345)",
    joinInputPlaceholder: "Distribution Code (e.g. 12345)",
    participantName: "Participant Name",
    imageMode: "Image Mode",
    loginRequiredMsg: "You must log in to select a part.",
    loginOrRegister: "Login or Register",
    guestSubtitle: "Spiritual connection platform",
    guestMessage:
      "Please login to join circles or create your own distribution.",
    guestCheckCode: "Just want to check a code?",
    guestCodePlaceholder: "Enter code",
    appTitle: "Read Circle",
    loginTitle: "Login",
    noAccount: "Don't have an account?",
    registerLink: "Register Now",
    loginError: "Invalid username or password",
    myCirclesTitle: "My Circles",
    noCirclesYet: "You haven't joined any circles yet.",
    continueButton: "CONTINUE",
    distCode: "Code",
    placeholderUser: "Your username",
    creatorLabel: "Creator",
  },
  ar: {
    title: "Read Circle",
    subtitle: "منصة توزيع القراءات",
    backHome: "الرئيسية",
    loginButton: "تسجيل الدخول",
    logoutButton: "تسجيل الخروج",
    guestRegister: "تسجيل",
    dashboard: "لوحة التحكم",

    landingHeroTitle: "الاتحاد الروحي",
    platform: "منصة",
    landingHeroSubtitle:
      "نظم ختمات القرآن وحلقات الجوشن وبرامج الأذكار بسهولة.",
    getStarted: "ابدأ الآن",
    sessionCodePlaceholder: "رمز الحلقة",
    join: "انضم",
    guestNote: "يمكنك الانضمام كضيف دون التسجيل.",

    featuresTitle1: "ختمات القرآن والجوشن",
    featuresDesc1: "وزع الأجزاء أو الصفحات تلقائيًا. تتبع التقدم مباشرة.",
    featuresTitle2: "حلقات الذكر المشترك",
    featuresDesc2: "ساهم في المجموعة المشتركة في الأذكار مثل الصلوات والدعاء.",
    featuresTitle3: "قراءة متوافقة مع الجوال",
    featuresDesc3: "اقرأ صفحات القرآن أو فصول الجوشن دون مغادرة التطبيق.",

    howItWorksTitle: "كيف يعمل؟",
    step1Title: "أنشئ جلسة",
    step1Desc: "حدد المصدر (ياسين، ختمة، إلخ) وعدد الأشخاص.",
    step2Title: "ادعُ الأصدقاء",
    step2Desc: "شارك الرمز القصير أو الرابط الذي تم إنشاؤه.",
    step3Title: "أكمل القراءة",
    step3Desc: "ليقرأ كل شخص جزأه، وشاهد التقدم فورًا.",

    welcome: "أهلاً بك،",
    dashboardIntro: "ماذا تريد أن تفعل في رحلتك الروحية اليوم؟",
    createNewSession: "أنشئ حلقة جديدة",
    managedSessions: "الحلقات التي أديرها",
    joinedSessions: "الحلقات التي انضممت إليها",
    noSessionYet: "لا يوجد بعد.",
    create: "إنشاء",
    codePlaceholder: "الرمز...",

    joinTitle: "الانضمام للحلقة",
    joinIntro: "الرجاء إدخال اسمك (ضيف)",
    yourName: "اسمك",
    distributedResources: "المصادر الموزعة",
    individualResources: "المصادر الفردية",
    takeRead: "أخذ",
    readText: "اقرأ",
    completed: "مكتمل",
    cancel: "إلغاء",
    page: "صفحة",
    previous: "السابق",
    next: "التالي",
    confirmComplete: "هل تؤكد أنك أتممت هذا الجزء؟",
    confirmCancel: "هل تريد إلغاء قراءة هذا الجزء؟",
    cancelFailed: "فشل الإلغاء.",
    connectionError: "خطأ في الاتصال.",
    errorFetchFailed: "فشل جلب البيانات. رمز الخطأ:",
    unexpectedError: "حدث خطأ غير متوقع.",
    readingTitle: "القراءة",
    closeWindow: "إغلاق النافذة",
    close: "إغلاق",
    chapter: "فصل",
    group: "مجموعة",
    translationTitle: "الترجمة",
    translationPending: "الترجمة قيد الانتظار...",
    arabicPage: "الصفحة العربية",
    meaningPage: "صفحة المعاني",
    otherResource: "آخر",
    confirmDeleteSession:
      "هل أنت متأكد من حذف هذه الجلسة نهائياً؟ ستفقد جميع البيانات.",
    confirmLeaveSession:
      "أنت على وشك مغادرة هذه الحلقة. سيتم إلغاء جميع مهامك.",
    confirmResetSession:
      "هل أنت متأكد من إعادة تعيين هذا التوزيع؟ سيتم إزالة جميع المشاركين وإعادة تعيين القراءات.",
    resetSuccess: "تم إعادة تعيين الجلسة بنجاح! في انتظار مشاركين جدد.",
    resetFailPrefix: "فشل إعادة التعيين: ",
    deleteSuccess: "تم حذف الجلسة بنجاح.",
    deleteFail: "فشل الحذف.",
    leaveSuccess: "لقد غادرت الحلقة.",
    leaveFail: "فشل مغادرة الحلقة.",
    reset: "إعادة تعيين / بدء من جديد",
    leave: "مغادرة",
    errorOccurred: "حدث خطأ.",
    menuLanguage: "إعدادات اللغة",
    footerDesc: "منصة التواصل الروحي وتوزيع الموارد.",
    rightsReserved: "جميع الحقوق محفوظة.",
    allahAccept: "تقبل الله.",
    adminButton: "دخول كمسؤول!",
    loading: "جاري التحميل...",
    delete: "حذف",
    confirmDelete: "هل أنت متأكد أنك تريد حذف هذا التوزيع؟",
    deletedSuccess: "تم حذف التوزيع.",
    adminTitle: "لوحة التحكم",
    setTargetCounts: "تعيين الأعداد المستهدفة (اختياري)",
    default: "افتراضي",
    participantCount: "عدد المشاركين؟",
    createDistribution: "إنشاء توزيع",
    linkCreated: "تم إنشاء الرابط:",
    copy: "نسخ",
    alertSelectResource: "الرجاء تحديد مورد واحد على الأقل.",
    confirmReset:
      "سيتم إعادة تعيين قاعدة البيانات إلى البيانات الافتراضية. هل أنت متأكد؟",
    refresh: "تحميل / إعادة تعيين البيانات",
    enterCode: "أدخل رمز التوزيع",
    joinButton: "انضمام",
    remaining: "المتبقي",
    tabArabic: "عربي",
    tabLatin: "نطق",
    tabMeaning: "ترجمة",
    successReset: "تمت إعادة التعيين بنجاح!",
    successDelete: "تم الحذف!",
    clickToCount: "انقر أثناء القراءة",
    person: "شخص",
    part: "جزء",
    target: "الهدف",
    total: "الإجمالي",
    pieces: "قطع",
    myCreatedTitle: "توزيعاتي",
    noCreatedYet: "لم تبدأ أي توزيع بعد.",
    trackButton: "إظهار الحالة",
    selectAndRead: "تحديد وقراءة",
    full: "مأخوذ",
    alertEnterName: "الرجاء إدخال اسمك أعلاه أولاً.",
    alertStatus: "الحالة: ",
    alertTakenSuccess: "رائع! لقد أخذت هذا الجزء بنجاح.",
    alertErrorPrefix: "خطأ: ",
    errorInvalidCode: "خطأ: رمز غير صالح أو الخادم معطل.",
    decrease: "إنقاص",
    errorAlreadyTaken: "للاسف، تم أخذ هذا الجزء من قبل شخص آخر.",
    registerTitle: "إنشاء حساب",
    finished: "إذا انتهيت، اضغط هنا",
    registerSubtitle: "أدخل بياناتك للانضمام إلينا",
    usernameLabel: "اسم المستخدم",
    passwordLabel: "كلمة المرور",
    placeholderUserExample: "مثال: ahmed123",
    placeholderPass: "******",
    registerButton: "تسجيل",
    registering: "جاري التسجيل...",
    haveAccount: "لديك حساب بالفعل؟",
    loginLink: "دخول",
    registerSuccess: "تم التسجيل بنجاح! يمكنك الدخول الآن.",
    errorPrefix: "خطأ: ",
    monitorTitle: "مراقب التوزيع",
    monitorSubtitle: "أدخل رمزاً للتحقق من من أخذ ماذا.",
    statusEmpty: "متاح",
    statusTaken: "مأخوذ",
    assignedTo: "مخصص لـ",
    resource: "مورد / جزء",
    progress: "التقدم / الهدف",
    backToAdmin: "العودة للوحة التحكم",
    occupancy: "الإشغال",
    statusHeader: "الحالة",
    targetLabel: "الهدف",
    select: "تحديد",
    cancelRead: "إلغاء القراءة",
    createDistTitle: "بدء حلقة جديدة",
    createDistDesc: "أنشئ حلقة قرآن أو يس أو ذكر وشارك الرابط.",
    joinDistTitle: "الانضمام لحلقة",
    joinDistDesc: "أدخل الرمز المشارك معك للمشاركة.",
    createButton: "إنشاء",
    enterCodePlaceholder: "رمز التوزيع (مثال: 12345)",
    joinInputPlaceholder: "رمز التوزيع (مثال: 12345)",
    participantName: "اسم المشارك",
    imageMode: "وضع الصورة",
    loginRequiredMsg: "يجب تسجيل الدخول لتحديد جزء.",
    loginOrRegister: "دخول أو تسجيل",
    guestSubtitle: "منصة التواصل الروحي",
    guestMessage: "الرجاء تسجيل الدخول للانضمام للحلقات أو إنشاء توزيعك الخاص.",
    guestCheckCode: "تريد فقط التحقق من رمز؟",
    guestCodePlaceholder: "أدخل الرمز",
    appTitle: "Read Circle",
    loginTitle: "تسجيل الدخول",
    noAccount: "ليس لديك حساب؟",
    registerLink: "سجل الآن",
    loginError: "اسم المستخدم أو كلمة المرور غير صالحة",
    myCirclesTitle: "حلقاتي",
    noCirclesYet: "لم تنضم لأي حلقات بعد.",
    continueButton: "متابعة",
    distCode: "الرمز",
    placeholderUser: "اسم المستخدم الخاص بك",
    creatorLabel: "المنشئ",
  },
  fr: {
    title: "Read Circle",
    subtitle: "Plateforme de Distribution de Ressources",
    backHome: "Accueil",
    dashboard: "Tableau de bord",

    landingHeroTitle: "Union Spirituelle",
    platform: "Plateforme",
    landingHeroSubtitle:
      "Organisez facilement des khatms du Coran, des cercles de Cevshen et des programmes de dhikr.",
    getStarted: "Commencer",
    sessionCodePlaceholder: "Session Code",
    join: "Rejoindre",
    guestNote: "Vous pouvez également rejoindre en tant qu'invité.",

    featuresTitle1: "Khatms Coran & Cevshen",
    featuresDesc1:
      "Distribuez automatiquement des juz ou des pages. Suivez la progression en direct.",
    featuresTitle2: "Cercles de Dhikr Communs",
    featuresDesc2:
      "Contribuez au pot commun pour les dhikrs comme les Salawats.",
    featuresTitle3: "Lecture Mobile",
    featuresDesc3:
      "Lisez les pages du Coran ou les sections de Cevshen sans quitter l'application.",

    howItWorksTitle: "Comment ça marche ?",
    step1Title: "Créer une session",
    step1Desc: "Sélectionnez la ressource et le nombre de personnes.",
    step2Title: "Inviter",
    step2Desc: "Partagez le code court ou le lien généré.",
    step3Title: "Terminer",
    step3Desc: "Chacun lit sa partie, visualisez les progrès instantanément.",
    welcome: "Bienvenue,",
    dashboardIntro:
      "Que voulez-vous faire dans votre voyage spirituel aujourd'hui ?",
    createNewSession: "Créer un nouveau cercle",
    managedSessions: "Cercles gérés",
    joinedSessions: "Cercles rejoints",
    noSessionYet: "Pas encore.",
    create: "Créer",
    codePlaceholder: "Code...",

    joinTitle: "Rejoindre le cercle",
    joinIntro: "Veuillez entrer votre nom (Invité)",
    yourName: "Votre Nom",
    distributedResources: "Ressources Partagées",
    individualResources: "Ressources Individuelles",
    takeRead: "PRENDRE",
    readText: "Lire",
    completed: "Terminé",
    cancel: "Annuler",
    page: "Page",
    previous: "Précédent",
    next: "Suivant",
    loginButton: "CONNEXION",
    logoutButton: "Déconnexion",
    guestRegister: "S'inscrire",
    confirmComplete: "Confirmez-vous avoir terminé cette partie ?",
    confirmCancel: "Voulez-vous annuler la lecture de cette partie ?",
    cancelFailed: "Annulation échouée.",
    connectionError: "Erreur de connexion.",
    errorFetchFailed: "Échec de récupération des données. Code d'erreur :",
    unexpectedError: "Une erreur inattendue est survenue.",
    readingTitle: "Lecture",
    closeWindow: "Fermer la fenêtre",
    close: "Fermer",
    chapter: "Chapitre",
    group: "Groupe",
    translationTitle: "Traduction",
    translationPending: "Traduction en attente...",
    arabicPage: "Page Arabe",
    meaningPage: "Page de Sens",
    otherResource: "Autre",
    confirmDeleteSession:
      "Êtes-vous sûr de vouloir supprimer cette session définitivement ? Toutes les données seront perdues.",
    confirmLeaveSession:
      "Vous êtes sur le point de quitter ce cercle. Toutes vos tâches seront annulées.",
    confirmResetSession:
      "Êtes-vous sûr de vouloir réinitialiser cette distribution ? Tous les participants seront retirés et les lectures remises à zéro.",
    resetSuccess:
      "Session réinitialisée avec succès ! En attente de nouveaux participants.",
    resetFailPrefix: "Échec de la réinitialisation : ",
    deleteSuccess: "Session supprimée avec succès.",
    deleteFail: "Échec de la suppression.",
    leaveSuccess: "Vous avez quitté le cercle.",
    leaveFail: "Échec lors de la tentative de quitter le cercle.",
    reset: "Réinitialiser / Redémarrer",
    leave: "Quitter",
    errorOccurred: "Une erreur est survenue.",
    menuLanguage: "Paramètres de langue",
    footerDesc:
      "Plateforme de connexion spirituelle et de distribution de ressources.",
    rightsReserved: "Tous droits réservés.",
    allahAccept: "Qu'Allah l'accepte.",
    adminButton: "Connexion Admin !",
    loading: "Chargement...",
    delete: "Supprimer",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer cette distribution ?",
    deletedSuccess: "Distribution supprimée.",
    adminTitle: "Tableau de bord Admin",
    setTargetCounts: "Définir les objectifs (Optionnel)",
    default: "Défaut",
    participantCount: "Nombre de participants ?",
    createDistribution: "CRÉER UNE DISTRIBUTION",
    linkCreated: "Lien créé :",
    copy: "Copier",
    alertSelectResource: "Veuillez sélectionner au moins une ressource.",
    confirmReset:
      "La base de données sera réinitialisée aux données par défaut. Êtes-vous sûr ?",
    refresh: "Charger / Réinitialiser les données",
    enterCode: "Entrez le code de distribution",
    joinButton: "Rejoindre",
    remaining: "Restant",
    tabArabic: "Arabe",
    tabLatin: "Transcription",
    tabMeaning: "Traduction",
    successReset: "Réinitialisation réussie !",
    successDelete: "Supprimé !",
    clickToCount: "CLIQUEZ PENDANT LA LECTURE",
    person: "Personne",
    part: "Partie",
    target: "Cible",
    total: "Total",
    pieces: "Pièces",
    myCreatedTitle: "Mes Distributions",
    noCreatedYet: "Vous n'avez pas encore commencé de distribution.",
    trackButton: "Voir l'état",
    selectAndRead: "SÉLECTIONNER & LIRE",
    full: "PRIS",
    alertEnterName: "Veuillez d'abord entrer votre nom ci-dessus.",
    alertStatus: "Statut : ",
    alertTakenSuccess: "Super ! Vous avez pris cette partie avec succès.",
    alertErrorPrefix: "Erreur : ",
    errorInvalidCode: "Erreur : Code invalide ou serveur hors ligne.",
    decrease: "DIMINUER",
    errorAlreadyTaken:
      "Malheureusement, cette partie a déjà été prise par quelqu'un d'autre.",
    registerTitle: "Créer un compte",
    finished: "Si vous avez terminé, cliquez",
    registerSubtitle: "Entrez vos détails pour nous rejoindre",
    usernameLabel: "Nom d'utilisateur",
    passwordLabel: "Mot de passe",
    placeholderUserExample: "ex: jean123",
    placeholderPass: "******",
    registerButton: "S'INSCRIRE",
    registering: "Inscription en cours...",
    haveAccount: "Vous avez déjà un compte ?",
    loginLink: "Connexion",
    registerSuccess: "Inscription réussie ! Vous pouvez vous connecter.",
    errorPrefix: "Erreur : ",
    monitorTitle: "Moniteur de Distribution",
    monitorSubtitle: "Entrez un code pour voir qui a pris quoi.",
    statusEmpty: "DISPONIBLE",
    statusTaken: "PRIS",
    assignedTo: "Attribué à",
    resource: "Ressource / Partie",
    progress: "Progrès / Cible",
    backToAdmin: "Retour au tableau de bord",
    occupancy: "OCCUPATION",
    statusHeader: "Statut",
    targetLabel: "CIBLE",
    select: "SÉLECTIONNER",
    cancelRead: "Annuler la lecture",
    createDistTitle: "Démarrer un nouveau cercle",
    createDistDesc:
      "Créez un cercle Coran, Yasin ou Dhikr et partagez le lien.",
    joinDistTitle: "Rejoindre un cercle",
    joinDistDesc: "Entrez le code partagé avec vous pour participer.",
    createButton: "CRÉER",
    enterCodePlaceholder: "Code de distribution (ex: 12345)",
    joinInputPlaceholder: "Code de distribution (ex: 12345)",
    participantName: "Nom du participant",
    imageMode: "Mode Image",
    loginRequiredMsg: "Vous devez vous connecter pour sélectionner une partie.",
    loginOrRegister: "Connexion ou Inscription",
    guestSubtitle: "Plateforme de connexion spirituelle",
    guestMessage:
      "Veuillez vous connecter pour rejoindre des cercles ou créer votre propre distribution.",
    guestCheckCode: "Voulez-vous juste vérifier un code ?",
    guestCodePlaceholder: "Entrer le code",
    appTitle: "Read Circle",
    loginTitle: "Connexion",
    noAccount: "Pas de compte ?",
    registerLink: "S'inscrire maintenant",
    loginError: "Nom d'utilisateur ou mot de passe invalide",
    myCirclesTitle: "Mes Cercles",
    noCirclesYet: "Vous n'avez rejoint aucun cercle pour le moment.",
    continueButton: "CONTINUER",
    distCode: "Code",
    placeholderUser: "Votre nom d'utilisateur",
    creatorLabel: "Créateur",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("tr");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("appLanguage") as Language;

    if (
      savedLanguage &&
      (savedLanguage === "tr" ||
        savedLanguage === "en" ||
        savedLanguage === "ku" ||
        savedLanguage === "ar" ||
        savedLanguage === "fr")
    ) {
      if (savedLanguage !== language) {
        setLanguageState(savedLanguage);
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("appLanguage", lang);
  };

  const t = (key: string): string => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const langData = (translations as any)[language];
    return langData?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
