"use client";

import React, {
  createContext,
  useContext,
  useState,
  ReactNode,
  useEffect,
} from "react";
import { Language } from "@/types";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

const translations = {
  tr: {
    common: {
      appTitle: "Spiritual Union for Reflection & Affinity",
      subtitle: "Kaynak Dağıtım Platformu",
      backHome: "Ana Sayfa",
      footerDesc: "Manevi birliktelik ve kaynak dağıtım platformu.",
      rightsReserved: "Tüm hakları saklıdır.",
      allahAccept: "Allah kabul etsin.",
      loading: "Yükleniyor...",
      close: "Kapat",
      leaveSession: "Oturumdan ayrıl",

      cancel: "İptal",
      codeCopied: "Kod kopyalandı",
      distributed: "Dağıtıldı",
      delete: "Sil",
      fixedResources: "Bireysel Kaynaklar",
      copy: "Kopyala",
      createNewOne: "Yeni bir tane daha oluştur",
      select: "SEÇ",
      sharedResources: "Paylaşımlı Kaynaklar",
      resource_YASIN: "Yasin Suresi",
      resource_FETIH: "Fetih Suresi",
      resource_CEVSEN: "Cevşenü'l Kebir",
      resource_TEFRICIYE: "Salat-ı Tefriciye",
      resource_MUNCIYE: "Salat-ı Münciye",
      resource_TEVHIDNAME: "Tevhidname",
      resource_UHUD: "Uhud Şehitleri",
      resource_BEDIR: "Bedir Şehitleri",
      resource_SALAVAT: "Salavat-ı Şerife",
      page: "Sayfa",
      startReading: "Okumaya Başla",

      part: "Parça",
      person: "Kişi",
      total: "Toplam",
      pieces: "Adet",
      menuLanguage: "Dil Ayarları",
      default: "Varsayılan",
      otherResource: "Diğer",
      copied: "Kopyalandı",
      sessionCreated: "Halka Oluşturuldu",
      giveUp: "Vazgeç",
      imageMode: "Resim Modu",
      continueButton: "DEVAM ET",
      adminButton: "Admin olarak giriş yap!",
    },
    auth: {
      loginTitle: "Giriş Yap",
      loginButton: "GİRİŞ YAP",
      logoutButton: "Çıkış Yap",
      registerTitle: "Hesap Oluştur",
      registerSubtitle: "Aramıza katılmak için bilgilerinizi girin",
      registerButton: "KAYIT OL",
      guestRegister: "Kayıt Ol",
      guestLogin: "Giriş Yap",
      guestSubtitle: "Manevi birliktelik platformu",
      guestMessage:
        "Halkalara katılmak veya kendi dağıtımını oluşturmak için lütfen giriş yap.",
      guestNote: "Kayıt olmadan misafir olarak da katılabilirsiniz.",
      usernameLabel: "Kullanıcı Adı",
      passwordLabel: "Şifre",
      placeholderUser: "Kullanıcı adınız",
      placeholderUserExample: "Örn: ahmet123",
      placeholderPass: "******",
      haveAccount: "Zaten hesabınız var mı?",
      noAccount: "Hesabın yok mu?",
      loginLink: "Giriş Yap",
      registerLink: "Hemen Kayıt Ol",
      loginError: "Kullanıcı adı veya şifre hatalı",
      registerSuccess: "Kayıt Başarılı! Giriş yapabilirsiniz.",
      registering: "Kaydediliyor...",
      loginRequiredMsg: "Parça seçmek için giriş yapmalısınız.",
      loginOrRegister: "Giriş Yap veya Kayıt Ol",
    },
    landing: {
      landingHeroTitle: "Manevî Birlik Platformu",
      landingHeroSubtitle:
        "Kuran hatimleri, Cevşen halkaları ve zikir programlarınızı kolayca organize edin. Sevdiklerinizle birlikte manevi hedeflerinize ulaşın.",
      getStarted: "Hemen Başla",
      featuresTitle1: "Kuran & Cevşen Hatimleri",
      featuresDesc1:
        "Cüzleri veya sayfaları otomatik dağıtın. Kimin nerede kaldığını canlı takip edin.",
      featuresTitle2: "Ortak Zikir Halkaları",
      featuresDesc2:
        "Salavat, dua ve zikir gibi hayırlarda ortak havuza katkıda bulunun.",
      featuresTitle3: "Mobil Uyumlu Okuma",
      featuresDesc3:
        "Uygulama içinden ayrılmadan Kuran sayfalarını, Cevşen bablarını veya zikirleri okuyun.",
      howItWorksTitle: "Nasıl Çalışır?",
      step1Title: "Oturum Oluştur",
      step1Desc:
        "Okunacak kaynağı (Yasin, Hatim vb.) ve kişi sayısını belirle.",
      step2Title: "Davet Et",
      step2Desc: "Oluşan kısa kodu veya linki sevdiklerinle paylaş.",
      step3Title: "Tamamla",
      step3Desc: "Herkes kendi parçasını alıp okusun, ilerlemeyi anlık gör.",
    },
    dashboard: {
      dashboard: "Panel",
      welcome: "Merhaba",
      dashboardIntro: "Bugün manevi yolculuğunda neler yapmak istersin?",
      myCirclesTitle: "Katıldığım Halkalar",
      myCreatedTitle: "Yönettiğim Dağıtımlar",
      joinedSessions: "Katıldığım halkalar",
      managedSessions: "Dağıttığım halkalar",
      createNewSession: "Yeni Halka Oluştur",
      noCirclesYet: "Henüz bir halkaya katılmadın.",
      noCreatedYet: "Henüz bir dağıtım başlatmadın.",
      noSessionYet: "Henüz yok.",
      create: "Oluştur",
      copyLink: "Linki kopyala",
      join: "Katıl",
      trackButton: "Takip Et",
      backToAdmin: "Admin Paneline Dön",
      adminTitle: "Yönetim Paneli",
    },
    distribution: {
      createDistTitle: "Yeni Dağıtım Başlat",
      createDistDesc: "Hatim, Yasin veya Zikir halkası oluşturup linki paylaş.",
      joinDistTitle: "Bir Halkaya Katıl",
      joinDistDesc: "Sana gönderilen kodu aşağıya girerek dahil ol.",
      createButton: "OLUŞTUR",
      yourTask: "Senin gorevin",
      joinButton: "Katıl",
      sessionCodePlaceholder: "Mevcut kod",
      pasteCodeOrLink: "Kodu veya linki yapıştır",
      enterCodePlaceholder: "Dağıtım Kodu (Örn: 12345)",
      guestCheckCode: "Sadece bir koda bakmak mı istiyorsun?",
      guestCodePlaceholder: "Kod giriniz",
      participantCount: "Kaç Kişi Okuyacak?",
      setTargetCounts: "Hedef Sayıları Belirle (Opsiyonel)",
      createDistribution: "DAĞITIMI OLUŞTUR",
      homeVerseContent:
        "Bilesiniz ki, kalpler ancak Allah'ı anmakla huzur bulur.",
      linkCreated: "Link Oluşturuldu:",
      monitorTitle: "Dağıtım Takibi",
      monitorSubtitle: "Bir kod girerek kimin ne aldığını kontrol edin.",
      distCode: "Kod",
      statusHeader: "Durum",
      assignedTo: "Alan Kişi",
      resource: "Kaynak / Parça",
      copyCode: "Kodu kopyala",

      progress: "İlerleme / Hedef",
      occupancy: "DOLULUK",
      targetLabel: "Hedef",
      deleteSession: "Oturumu sil",
      remaining: "Kalan",
      distributedResources: "Bölüştürülecek Kaynaklar",
      individualResources: "Bireysel Kaynaklar",
      creatorLabel: "Kurucu",
    },
    reading: {
      readingTitle: "Okuma",
      joinTitle: "Halkaya Katıl",
      joinIntro: "Lütfen adınızı giriniz (Misafir)",
      yourName: "Adınız",
      takeRead: "AL",
      readText: "Oku",
      completed: "Tamamlandı",
      finish: "Tamamladıysan tıkla",
      selectAndRead: "SEÇ & OKU",
      clickToCount: "OKUDUKÇA TIKLAYINIZ",
      decrease: "AZALT",
      closeWindow: "Pencereyi Kapat",
      chapter: "BAB",
      group: "Grup",
      translationTitle: "Türkçe Meali",
      translationPending: "Çeviri hazırlanıyor...",
      arabicPage: "Arapça Sayfa",
      meaningPage: "Meal Sayfa",
      tabArabic: "Arapça",
      tabLatin: "Okunuş",
      tabMeaning: "Meal",
      previous: "Önceki",
      next: "Sonraki",
      statusEmpty: "BOŞTA",
      statusTaken: "ALINDI",
      full: "DOLU",
      participantName: "Katılımcı Adı",
      cancelRead: "Okumaktan Vazgeç",
    },
    alerts: {
      successReset: "Sıfırlandı!",
      successDelete: "Silindi!",
      errorOccurred: "Hata oluştu.",
      unexpectedError: "Beklenmedik bir hata oluştu.",
      connectionError: "Bağlantı hatası.",
      errorFetchFailed: "Veri alınamadı. Hata Kodu:",
      errorInvalidCode: "Hata: Geçersiz kod veya sunucu kapalı.",
      errorAlreadyTaken: "Bu parça maalesef başkası tarafından alınmış.",
      alertSelectResource: "Lütfen en az bir kaynak seçiniz.",
      alertEnterName: "Lütfen önce yukarıya isminizi yazın.",
      alertTakenSuccess: "Harika! Bu bölümü okumayı üstlendiniz.",
      confirmDelete: "Silmek istediğinize emin misiniz?",
      confirmDeleteSession:
        "Bu oturumu tamamen silmek istediğinize emin misiniz? Tüm veriler kaybolacak.",
      confirmLeaveSession:
        "Bu halkadan ayrılmak üzeresiniz. Aldığınız tüm görevler iptal edilecek.",
      confirmResetSession:
        "Bu dağıtımı sıfırlamak istediğinize emin misiniz? Tüm katılımcılar çıkarılacak ve okumalar sıfırlanacak.",
      confirmReset:
        "Tüm veritabanı sıfırlanıp varsayılan veriler yüklenecek. Emin misiniz?",
      confirmComplete: "Bu parçayı okuduğunuzu onaylıyor musunuz?",
      confirmCancel: "Bu parçayı okumaktan vazgeçmek istiyor musunuz?",
      resetSuccess:
        "Oturum başarıyla sıfırlandı! Yeni katılımcılar bekleniyor.",
      resetFailPrefix: "Sıfırlama başarısız: ",
      deleteSuccess: "Oturum başarıyla silindi.",
      deleteFail: "Silme işlemi başarısız oldu.",
      featureFree: "Ücretsiz Kullanım",
      featureNoLogin: "Üyeliksiz Katılım",
      leaveSuccess: "Halkadan ayrıldınız.",
      leaveFail: "Ayrılma işlemi başarısız oldu.",
      cancelFailed: "İptal edilemedi.",
      successLeave: "Halkadan başarıyla ayrıldınız.",
      resetSession: "Oturumu resetle",
      alertStatus: "Durum: ",
      errorPrefix: "Hata: ",
    },
  },
  ku: {
    common: {
      appTitle: "Spiritual Union for Reflection & Affinity",
      subtitle: "Platforma Belavkirina Çavkaniyan",
      backHome: "Mal",
      giveUp: "Dev jê bibe",
      pasteCodeOrLink: "Kod an girêdanê biçeşîne",
      fixedResources: "Çavkaniyên taybetî",
      codeCopied: "Kod hat kopîkirin",
      footerDesc: "Platforma yekîtiya manewî û belavkirina çavkaniyan.",
      rightsReserved: "Hemû maf parastî ne.",

      distributed: "Belav kirin",
      allahAccept: "Xwedê qebûl bike.",
      loading: "Tê barkirin...",
      close: "Bigire",

      copied: "Kopîkirî",
      sessionCreated: "Rûniştin çêbû",
      cancel: "Betal Bike",
      resource_YASIN: "Sûreya Yasin",
      resource_FETIH: "Sûreya Fetih",
      resource_CEVSEN: "Cewşenê Kebîr",
      resource_TEFRICIYE: "Salatê Tefriciye",
      resource_MUNCIYE: "Salatê Münciye",
      resource_TEVHIDNAME: "Tevhîdname",
      resource_UHUD: "Şehîdên Uhudê",
      resource_BEDIR: "Şehîdên Bedirê",
      resource_SALAVAT: "Salawatê Şerîfe",

      sharedResources: "Çavkaniyên parvekirî",
      delete: "Jê Bibe",
      copy: "Kopyake",
      select: "HILBIJÊRE",
      createNewOne: "Yek nû biafirîne",
      page: "Rûpel",
      targetLabel: "Armanc",

      part: "Parçe",
      person: "Kes",
      copyLink: "Linkê kopî bike",

      total: "Giştî",
      pieces: "Heb",
      menuLanguage: "Mîhengên Ziman",
      default: "Pêşwext",
      otherResource: "Yên din",
      imageMode: "Moda Wêneyê",
      continueButton: "DEWAM BIKE",
      adminButton: "Wekî Admin têkeve!",
    },
    auth: {
      loginTitle: "Têkeve",
      loginButton: "TÊKETIN",
      logoutButton: "Derketin",
      registerTitle: "Hesab Çêbike",
      registerSubtitle: "Ji bo tevlî me bibî agahiyên xwe binivîse",
      registerButton: "QEYD Bûyîn",
      guestRegister: "Qeyd Bibe",
      guestLogin: "Bikevê",
      resetSession: "Reset Session",

      guestSubtitle: "Platforma yekîtiya manewî",
      guestMessage:
        "Ji bo tevlî xelekan bibî an belavkirina xwe çêbikî ji kerema xwe têkeve.",
      guestNote: "Hûn dikarin bêyî qeydkirinê wekî mêvan tevlî bibin.",
      usernameLabel: "Navê Bikarhêner",
      passwordLabel: "Şîfre",
      placeholderUser: "Navê te yê bikarhêner",
      placeholderUserExample: "Mînak: azad123",
      placeholderPass: "******",
      haveAccount: "Ma hesabê te heye?",
      noAccount: "Ma hesabê te tune?",
      copyCode: "Kode kopî bike",

      loginLink: "Têkeve",
      registerLink: "Hemen Qeyd Bibe",
      loginError: "Navê bikarhêner an şîfre şaş e",
      registerSuccess: "Qeyd serkeftî bû! Niha dikarî têkevî.",
      registering: "Tê qeydkirin...",
      loginRequiredMsg: "Ji bo hilbijartina parçeyekê divê têkevî.",
      loginOrRegister: "Têkeve an Qeyd Bibe",
    },
    landing: {
      landingHeroTitle: "Platforma yekîtiya manewî",

      homeVerseContent: "Bi bîranîna Xwedê re tenê dilan aram dibin.",
      landingHeroSubtitle:
        "Xatimên Quranê, xelekên Cewşenê û bernameyên zikran bi hêsanî organîze bikin",
      getStarted: "Dest Pê Bike",
      yourTask: "Erka te",
      deleteSession: "Paqiş bike!",

      featuresTitle1: "Xatimên Quran & Cewşenê",
      featuresDesc1:
        "Cuz an rûpelan bixweber belav bikin. Zindî bişopînin kî li ku maye.",
      featuresTitle2: "Xelekên Zikrê Yên Hevpar",
      startReading: "Dest bi xwendinê bike",

      featuresDesc2:
        "Di zikran de mîna Selewat û duayan beşdarî hewza hevpar bibin.",
      featuresTitle3: "Xwendina Li Gorî Mobîlê",
      featuresDesc3:
        "Bêyî ku ji sepanê derkevin rûpelên Quranê an beşên Cewşenê bixwînin.",
      howItWorksTitle: "Çawa Dixebite?",
      step1Title: "Rûniştinê Ava Bike",
      step1Desc: "Çavkaniyê (Yasîn, Xatim hwd.) û hejmara kesan diyar bike.",
      step2Title: "Dawet Bike",
      step2Desc: "Koda kurt an lînka hatî çêkirin parve bike.",
      step3Title: "Temam Bike",
      step3Desc: "Her kes para xwe bixwîne, pêşveçûnê di cih de bibîne.",
    },
    dashboard: {
      dashboard: "Panel",
      welcome: "Bi xêr hatî,",
      dashboardIntro: "Îro di rêwîtiya xwe ya manewî de dixwazî çi bikî?",
      myCirclesTitle: "Xelekên Ez Tevlî Bûm",
      myCreatedTitle: "Belavkirinên Min ên Rêvebir",
      joinedSessions: "Xelekên Ez Tevlî Bûme",
      managedSessions: "Xelekên Ez Birêve Dibim",
      createNewSession: "Xeleka Nû Ava Bike",
      noCirclesYet: "Hêj tevlî tu xelekê nebûyî.",
      noCreatedYet: "Hêj te belavkirinek neda destpêkirin.",
      noSessionYet: "Hîn tune.",
      create: "Ava Bike",
      join: "Tevlî Bibe",
      trackButton: "Bişopîne",
      featureFree: "Bêpere bikar bînî",
      featureNoLogin: "Bê endamî beşdar bibe",
      backToAdmin: "Vegere Panela Admin",
      adminTitle: "Panela Rêveberiyê",
    },
    distribution: {
      createDistTitle: "Xeleka Nû Destpê Bike",
      createDistDesc:
        "Xeleka Hatim, Yasîn an Zikirê çêbike û lînkê parve bike.",
      joinDistTitle: "Tevlî Xelekê Bibe",
      joinDistDesc:
        "Koda ku ji te re hatiye şandin li jêr binivîse û beşdar bibe.",
      createButton: "PÊK BÎNE",
      joinButton: "Tevlî Bibe",
      sessionCodePlaceholder: "Koda Xelekê",
      enterCode: "Koda Belavkirinê Binivîse",
      enterCodePlaceholder: "Koda Belavkirinê (Mînak: 12345)",
      guestCheckCode: "Tenê dixwazî li kodekê binêrî?",
      guestCodePlaceholder: "Kod binivîse",
      participantCount: "Çend Kes Wê Bixwînin?",
      setTargetCounts: "Hejmarên Hedef Diyar Bike (Vebijarkî)",
      createDistribution: "BELAVKIRINÊ PÊK BÎNE",
      linkCreated: "Lînk Hat Çêkirin:",
      monitorTitle: "Şopandina Belavkirinê",
      monitorSubtitle: "Bi nivîsandina kodê kontrol bike ka kî çi girtiye.",
      distCode: "Kod",
      statusHeader: "Rewş",
      assignedTo: "Kesê Girtiye",
      resource: "Çavkanî / Parçe",
      progress: "Pêşveçûn / Hedef",
      occupancy: "TIJEBÛN",
      targetLabel: "Armanc",
      remaining: "Mayî",
      distributedResources: "Çavkaniyên Hatin Belavkirin",
      individualResources: "Çavkaniyên Bireysel",
      creatorLabel: "Avaker",
    },
    reading: {
      readingTitle: "Xwendin",
      joinTitle: "Tevlî Xelekê Bibe",
      joinIntro: "Navê xwe binivîse (Mêvan)",
      yourName: "Navê Te",
      takeRead: "BIGIRE",
      readText: "Bixwîne",
      completed: "Temam Bû",
      finish: "Heke te xelas kir, bitikîne",
      selectAndRead: "HILBIJÊRE & BIXWÎNE",
      clickToCount: "HER KU TE XWEND BITIKÎNE",
      decrease: "KÊM BIKE",
      closeWindow: "Pencereyê Bigire",
      successLeave: "Bi serkeftî ji rûniştinê derketî.",
      chapter: "BEŞ",
      group: "Kom",
      translationTitle: "Wateya Kurdî",
      translationPending: "Wergêr tê amadekirin...",
      arabicPage: "Rûpela Erebî",
      meaningPage: "Rûpela Wateyê",
      tabArabic: "Erebî",
      tabLatin: "Bilêvkirin",
      tabMeaning: "Wate",
      previous: "Pêş",
      next: "Paş",
      statusEmpty: "VALA",
      statusTaken: "HAT GIRTIN",
      full: "TIJE",
      participantName: "Navê Beşdar",
      cancelRead: "Xwendinê Betal Bike",
    },
    alerts: {
      successReset: "Hat Sifirkirin!",
      successDelete: "Hat Jêbirin!",
      errorOccurred: "Xetayek çêbû.",
      unexpectedError: "Xetayek neçaverêkirî çêbû.",
      connectionError: "Xetaya girêdanê.",
      errorFetchFailed: "Dâne nehatin standin. Koda Xetayê:",
      errorInvalidCode: "Xeta: Kod nederbasdar e an server girtî ye.",
      errorAlreadyTaken:
        "Mixabin, ev parçe ji aliyê kesekî din ve hatiye girtin.",
      alertSelectResource: "Ji kerema xwe qet nebe çavkaniyek hilbijêrin.",
      alertEnterName: "Ji kerema xwe pêşî navê xwe li jor binivîse.",
      alertTakenSuccess: "Gelek baş e! Te ev beş girt ser xwe.",
      confirmDelete: "Tu piştrast î ku dixwazî vê belavkirinê jê bibî?",
      confirmDeleteSession:
        "Tu piştrast î ku dixwazî vê xelekê bi temamî jê bibî? Hemû dane wê winda bibin.",
      confirmLeaveSession:
        "Tu li ber î ku ji vê xelekê derkevî. Hemû parçeyên te wê werin betalkirin.",
      confirmResetSession:
        "Tu piştrast î ku dixwazî vê xelekê sifir bikî? Hemû beşdar wê werin derxistin û xwendin wê werin sifirkirin.",
      confirmReset:
        "Hemû databas wê were sifirkirin û daneyên pêşwext werin barkirin. Tu piştrast î?",
      confirmComplete: "Tu piştrast î ku te ev beş xwendiye?",
      confirmCancel: "Tu dixwazî dev ji xwendina vê beşê berdî?",
      resetSuccess:
        "Xelek bi serkeftî hate sifirkirin! Li benda beşdarên nû ye.",
      resetFailPrefix: "Sifirkirin bi ser neket: ",
      leaveSession: "Ji rûniştinê derkeve",
      deleteSuccess: "Xelek bi serkeftî hate jêbirin.",
      deleteFail: "Jêbirin bi ser neket.",
      leaveSuccess: "Tu ji xelekê derketî.",
      leaveFail: "Derketina ji xelekê bi ser neket.",
      cancelFailed: "Betalkirin biser neket.",
      alertStatus: "Rewş: ",
      errorPrefix: "Xeta: ",
    },
  },
  en: {
    common: {
      appTitle: "Spiritual Union for Reflection & Affinity",
      subtitle: "Resource Distribution Platform",
      backHome: "Home",
      distributed: "Distributed",
      footerDesc: "Spiritual connection and resource distribution platform.",
      rightsReserved: "All rights reserved.",
      sessionCreated: "Session created",
      pasteCodeOrLink: "Paste code or link",
      allahAccept: "May Allah accept it.",
      fixedResources: "Fixed Resources",
      loading: "Loading...",
      resource_YASIN: "Surah Yaseen",
      resource_FETIH: "Surah Al-Fath",
      resource_CEVSEN: "Jawshan Kabir",
      resource_TEFRICIYE: "Salat al-Tefriciye",
      resource_MUNCIYE: "Salat al-Munciye",
      resource_TEVHIDNAME: "Tawhidname",
      resource_UHUD: "Martyrs of Uhud",
      resource_BEDIR: "Martyrs of Badr",
      resource_SALAVAT: "Salawat",
      close: "Close",
      sharedResources: "Shared Resources",
      createNewOne: "Create a new one",
      cancel: "Cancel",
      copied: "Copied",
      giveUp: "Give up",
      delete: "Delete",
      copy: "Copy",
      select: "SELECT",
      page: "Page",
      part: "Part",
      person: "Person",
      total: "Total",
      pieces: "Pieces",
      menuLanguage: "Language Settings",
      default: "Default",
      targetLabel: "Target",

      otherResource: "Other",
      imageMode: "Image Mode",
      continueButton: "CONTINUE",
      startReading: "Start Reading",

      adminButton: "Login as Admin!",
    },
    auth: {
      loginTitle: "Login",
      loginButton: "LOGIN",
      logoutButton: "Logout",
      registerTitle: "Create Account",
      registerSubtitle: "Enter your details to join us",
      registerButton: "REGISTER",
      guestRegister: "Register",
      guestLogin: "Login",
      leaveSession: "Leave session",

      resetSession: "Reset Session",
      featureFree: "Free to Use",
      featureNoLogin: "Join Without Login",
      guestSubtitle: "Spiritual connection platform",
      guestMessage:
        "Please login to join circles or create your own distribution.",
      guestNote: "You can also join as a guest without registering.",
      usernameLabel: "Username",
      passwordLabel: "Password",
      placeholderUser: "Your username",
      placeholderUserExample: "e.g. john123",
      placeholderPass: "******",
      haveAccount: "Already have an account?",
      noAccount: "Don't have an account?",
      loginLink: "Login",
      deleteSession: "Delete Session",

      registerLink: "Register Now",
      loginError: "Invalid username or password",
      registerSuccess: "Registration successful! You can login now.",
      registering: "Registering...",
      loginRequiredMsg: "You must log in to select a part.",
      loginOrRegister: "Login or Register",
    },
    landing: {
      landingHeroTitle: "Spiritual Union Platform",
      landingHeroSubtitle:
        "Easily organize Quran khatms, Cevshen circles, and dhikr programs. Achieve your spiritual goals with your loved ones.",
      getStarted: "Get Started",
      featuresTitle1: "Quran & Cevshen Khatms",
      featuresDesc1:
        "Distribute juz or pages automatically. Track who is where in real-time.",
      featuresTitle2: "Joint Dhikr Circles",
      featuresDesc2:
        "Contribute to the common pool in dhikrs like Salawat and prayers.",
      featuresTitle3: "Mobile Friendly Reading",
      featuresDesc3:
        "Read Quran pages or Cevshen sections without leaving the app.",
      howItWorksTitle: "How It Works?",
      step1Title: "Create Session",
      step1Desc:
        "Select the resource (Yasin, Khatm, etc.) and number of people.",
      step2Title: "Invite",
      step2Desc: "Share the generated short code or link.",
      step3Title: "Complete",
      step3Desc: "Everyone reads their part, see progress instantly.",
    },
    dashboard: {
      dashboard: "Dashboard",
      welcome: "Welcome",
      dashboardIntro:
        "What would you like to do on your spiritual journey today?",
      myCirclesTitle: "My Circles",
      myCreatedTitle: "My Distributions",
      joinedSessions: "Joined Circles",
      managedSessions: "Managed Circles",
      createNewSession: "Create New Circle",
      noCirclesYet: "You haven't joined any circles yet.",
      noCreatedYet: "You haven't started any distribution yet.",
      noSessionYet: "None yet.",
      create: "Create",
      join: "Join",
      copyCode: "Copy code",
      trackButton: "Show Status",
      backToAdmin: "Back to Dashboard",
      adminTitle: "Admin Dashboard",
    },
    distribution: {
      createDistTitle: "Start New Circle",
      createDistDesc:
        "Create a Quran, Yasin, or Dhikr circle and share the link.",
      joinDistTitle: "Join a Circle",
      joinDistDesc: "Enter the code shared with you to participate.",
      createButton: "CREATE",
      joinButton: "Join",
      sessionCodePlaceholder: "Session Code",
      enterCode: "Enter Distribution Code",
      enterCodePlaceholder: "Distribution Code (e.g. 12345)",
      guestCheckCode: "Just want to check a code?",
      guestCodePlaceholder: "Enter code",
      copyLink: "Copy link",
      participantCount: "Number of Participants?",
      setTargetCounts: "Set Target Counts (Optional)",
      createDistribution: "CREATE DISTRIBUTION",
      linkCreated: "Link Created:",
      monitorTitle: "Distribution Monitor",
      monitorSubtitle: "Enter a code to check who took what.",
      distCode: "Code",
      statusHeader: "Status",
      assignedTo: "Assigned To",
      resource: "Resource / Part",
      progress: "Progress / Target",
      occupancy: "OCCUPANCY",
      targetLabel: "TARGET",
      remaining: "Remaining",
      distributedResources: "Shared Resources",
      individualResources: "Individual Resources",
      creatorLabel: "Creator",
    },
    reading: {
      readingTitle: "Reading",
      joinTitle: "Join Circle",
      joinIntro: "Please enter your name (Guest)",
      yourName: "Your Name",
      yourTask: "Your Task",
      takeRead: "TAKE",
      readText: "Read",
      completed: "Completed",
      finish: "If you finished, click",
      selectAndRead: "SELECT & READ",
      clickToCount: "CLICK AS YOU READ",
      decrease: "DECREASE",
      closeWindow: "Close Window",
      chapter: "Chapter",
      group: "Group",
      translationTitle: "Translation",
      translationPending: "Translation pending...",
      arabicPage: "Arabic Page",
      meaningPage: "Meaning Page",
      tabArabic: "Arabic",
      tabLatin: "Transliteration",
      tabMeaning: "Translation",
      previous: "Previous",
      next: "Next",
      statusEmpty: "AVAILABLE",
      statusTaken: "TAKEN",
      full: "TAKEN",
      participantName: "Participant Name",
      cancelRead: "Cancel Reading",
    },
    alerts: {
      successReset: "Reset successful!",
      successDelete: "Deleted!",
      errorOccurred: "An error occurred.",
      unexpectedError: "An unexpected error occurred.",
      homeVerseContent:
        "Indeed, hearts find peace only in the remembrance of Allah.",

      connectionError: "Connection error.",
      errorFetchFailed: "Failed to fetch data. Error Code:",
      errorInvalidCode: "Error: Invalid code or server is down.",
      errorAlreadyTaken:
        "Unfortunately, this part has already been taken by someone else.",
      alertSelectResource: "Please select at least one resource.",
      alertEnterName: "Please enter your name above first.",
      alertTakenSuccess: "Great! You have successfully taken this part.",
      confirmDelete: "Are you sure you want to delete this distribution?",
      confirmDeleteSession:
        "Are you sure you want to delete this session permanently? All data will be lost.",
      confirmLeaveSession:
        "You are about to leave this circle. All your assignments will be cancelled.",
      confirmResetSession:
        "Are you sure you want to reset this distribution? All participants will be removed and readings reset.",
      confirmReset: "Database will be reset to default data. Are you sure?",
      confirmComplete: "Do you confirm that you have read this part?",
      confirmCancel: "Do you want to cancel reading this part?",
      resetSuccess: "Session successfully reset! Waiting for new participants.",
      resetFailPrefix: "Reset failed: ",
      deleteSuccess: "Session successfully deleted.",
      deleteFail: "Deletion failed.",
      leaveSuccess: "You have left the circle.",
      leaveFail: "Failed to leave the circle.",
      cancelFailed: "Could not cancel.",
      successLeave: "You have successfully left the session.",
      alertStatus: "Status: ",
      errorPrefix: "Error: ",
    },
  },
  ar: {
    common: {
      appTitle: "Spiritual Union for Reflection & Affinity",
      subtitle: "منصة توزيع القراءات",
      backHome: "الرئيسية",
      codeCopied: "تم نسخ الكود",
      pasteCodeOrLink: "رمز أو الصق الرابط",
      footerDesc: "منصة التواصل الروحي وتوزيع الموارد.",
      rightsReserved: "جميع الحقوق محفوظة.",
      allahAccept: "تقبل الله.",
      fixedResources: "الموارد الفردية",
      sessionCreated: "تم إنشاء الجلسة",
      resource_YASIN: "سورة يس",

      distributed: "تم التوزيع",

      resource_FETIH: "سورة الفتح",
      resource_CEVSEN: "جوشن الكبير",
      resource_TEFRICIYE: "الصلاة التفريجية",
      resource_MUNCIYE: "الصلاة المنجية",
      resource_TEVHIDNAME: "توحيدنامه",
      resource_UHUD: "شهداء أحد",
      resource_BEDIR: "شهداء بدر",
      resource_SALAVAT: "الصلاة الشريفة",

      loading: "جاري التحميل...",
      close: "إغلاق",
      sharedResources: "الموارد المشتركة",
      createNewOne: "إنشاء واحدة جديدة",
      cancel: "إلغاء",
      delete: "حذف",
      resetSession: "إعادة تعيين الجلسة",

      copied: "تم النسخ",
      copy: "نسخ",
      select: "تحديد",
      page: "صفحة",
      part: "جزء",
      person: "شخص",
      total: "الإجمالي",
      pieces: "قطع",
      menuLanguage: "إعدادات اللغة",
      default: "افتراضي",
      startReading: "ابدأ القراءة",

      otherResource: "آخر",
      imageMode: "وضع الصورة",
      continueButton: "متابعة",
      adminButton: "دخول كمسؤول!",
    },
    auth: {
      loginTitle: "تسجيل الدخول",
      loginButton: "تسجيل الدخول",
      logoutButton: "تسجيل الخروج",
      registerTitle: "إنشاء حساب",
      registerSubtitle: "أدخل بياناتك للانضمام إلينا",
      registerButton: "تسجيل",
      guestRegister: "تسجيل",
      guestLogin: "دخول",
      guestSubtitle: "منصة التواصل الروحي",
      guestMessage:
        "الرجاء تسجيل الدخول للانضمام للحلقات أو إنشاء توزيعك الخاص.",
      guestNote: "يمكنك الانضمام كضيف دون التسجيل.",
      usernameLabel: "اسم المستخدم",
      passwordLabel: "كلمة المرور",
      placeholderUser: "اسم المستخدم الخاص بك",
      placeholderUserExample: "مثال: ahmed123",
      placeholderPass: "******",
      haveAccount: "لديك حساب بالفعل؟",
      noAccount: "ليس لديك حساب؟",
      loginLink: "دخول",
      registerLink: "سجل الآن",
      loginError: "اسم المستخدم أو كلمة المرور غير صالحة",
      registerSuccess: "تم التسجيل بنجاح! يمكنك الدخول الآن.",
      registering: "جاري التسجيل...",
      loginRequiredMsg: "يجب تسجيل الدخول لتحديد جزء.",
      loginOrRegister: "دخول أو تسجيل",
    },
    landing: {
      landingHeroTitle: "منصة الاتحاد الروحي",
      landingHeroSubtitle:
        "نظم ختمات القرآن وحلقات الجوشن وبرامج الأذكار بسهولة.",
      getStarted: "ابدأ الآن",
      deleteSession: "حذف الجلسة",
      featuresTitle1: "ختمات القرآن والجوشن",
      featuresDesc1: "وزع الأجزاء أو الصفحات تلقائيًا. تتبع التقدم مباشرة.",
      featuresTitle2: "حلقات الذكر المشترك",
      featuresDesc2:
        "ساهم في المجموعة المشتركة في الأذكار مثل الصلوات والدعاء.",
      featuresTitle3: "قراءة متوافقة مع الجوال",
      featuresDesc3: "اقرأ صفحات القرآن أو فصول الجوشن دون مغادرة التطبيق.",
      howItWorksTitle: "كيف يعمل؟",
      step1Title: "أنشئ جلسة",
      step1Desc: "حدد المصدر (ياسين، ختمة، إلخ) وعدد الأشخاص.",
      step2Title: "ادعُ الأصدقاء",
      step2Desc: "شارك الرمز القصير أو الرابط الذي تم إنشاؤه.",
      step3Title: "أكمل القراءة",
      step3Desc: "ليقرأ كل شخص جزأه، وشاهد التقدم فورًا.",
    },
    dashboard: {
      dashboard: "لوحة التحكم",
      welcome: "أهلاً بك،",
      dashboardIntro: "ماذا تريد أن تفعل في رحلتك الروحية اليوم؟",
      myCirclesTitle: "حلقاتي",
      myCreatedTitle: "توزيعاتي",
      joinedSessions: "الحلقات التي انضممت إليها",
      managedSessions: "الحلقات التي أديرها",
      createNewSession: "أنشئ حلقة جديدة",
      noCirclesYet: "لم تنضم لأي حلقات بعد.",
      noCreatedYet: "لم تبدأ أي توزيع بعد.",
      noSessionYet: "لا يوجد بعد.",
      create: "إنشاء",
      join: "انضم",
      trackButton: "إظهار الحالة",
      backToAdmin: "العودة للوحة التحكم",
      adminTitle: "لوحة التحكم",
    },
    distribution: {
      createDistTitle: "بدء حلقة جديدة",
      createDistDesc: "أنشئ حلقة قرآن أو يس أو ذكر وشارك الرابط.",
      joinDistTitle: "الانضمام لحلقة",
      joinDistDesc: "أدخل الرمز المشارك معك للمشاركة.",
      homeVerseContent: " ",

      createButton: "إنشاء",
      joinButton: "انضمام",
      sessionCodePlaceholder: "رمز الحلقة",
      enterCode: "أدخل رمز التوزيع",
      enterCodePlaceholder: "رمز التوزيع (مثال: 12345)",
      guestCheckCode: "تريد فقط التحقق من رمز؟",
      guestCodePlaceholder: "أدخل الرمز",
      participantCount: "عدد المشاركين؟",
      setTargetCounts: "تعيين الأعداد المستهدفة (اختياري)",
      createDistribution: "إنشاء توزيع",
      linkCreated: "تم إنشاء الرابط:",
      yourTask: "مهمتك",
      monitorTitle: "مراقب التوزيع",
      monitorSubtitle: "أدخل رمزاً للتحقق من من أخذ ماذا.",
      distCode: "الرمز",
      statusHeader: "الحالة",
      assignedTo: "مخصص لـ",
      resource: "مورد / جزء",
      progress: "التقدم / الهدف",
      occupancy: "الإشغال",
      targetLabel: "الهدف",
      remaining: "المتبقي",
      copyLink: "نسخ الرابط",
      distributedResources: "المصادر الموزعة",
      individualResources: "المصادر الفردية",
      creatorLabel: "المنشئ",
    },
    reading: {
      readingTitle: "القراءة",
      joinTitle: "الانضمام للحلقة",
      joinIntro: "الرجاء إدخال اسمك (ضيف)",
      yourName: "اسمك",
      takeRead: "أخذ",
      readText: "اقرأ",
      completed: "مكتمل",
      finish: "إذا انتهيت، اضغط هنا",
      selectAndRead: "تحديد وقراءة",
      clickToCount: "انقر أثناء القراءة",
      decrease: "إنقاص",
      closeWindow: "إغلاق النافذة",
      chapter: "فصل",
      group: "مجموعة",
      translationTitle: "الترجمة",
      translationPending: "الترجمة قيد الانتظار...",
      arabicPage: "الصفحة العربية",
      meaningPage: "صفحة المعاني",
      tabArabic: "عربي",
      tabLatin: "نطق",
      targetLabel: "هدف",
      tabMeaning: "ترجمة",
      giveUp: "استسلام",
      previous: "السابق",
      next: "التالي",
      statusEmpty: "متاح",
      statusTaken: "مأخوذ",
      full: "مأخوذ",
      participantName: "اسم المشارك",
      cancelRead: "إلغاء القراءة",
    },
    alerts: {
      successReset: "تمت إعادة التعيين بنجاح!",
      successDelete: "تم الحذف!",
      errorOccurred: "حدث خطأ.",
      unexpectedError: "حدث خطأ غير متوقع.",
      connectionError: "خطأ في الاتصال.",
      errorFetchFailed: "فشل جلب البيانات. رمز الخطأ:",
      errorInvalidCode: "خطأ: رمز غير صالح أو الخادم معطل.",
      errorAlreadyTaken: "للاسف، تم أخذ هذا الجزء من قبل شخص آخر.",
      alertSelectResource: "الرجاء تحديد مورد واحد على الأقل.",
      alertEnterName: "الرجاء إدخال اسمك أعلاه أولاً.",
      alertTakenSuccess: "رائع! لقد أخذت هذا الجزء بنجاح.",
      leaveSession: "مغادرة الجلسة",
      confirmDelete: "هل أنت متأكد أنك تريد حذف هذا التوزيع؟",
      confirmDeleteSession:
        "هل أنت متأكد من حذف هذه الجلسة نهائياً؟ ستفقد جميع البيانات.",
      confirmLeaveSession:
        "أنت على وشك مغادرة هذه الحلقة. سيتم إلغاء جميع مهامك.",
      confirmResetSession:
        "هل أنت متأكد من إعادة تعيين هذا التوزيع؟ سيتم إزالة جميع المشاركين وإعادة تعيين القراءات.",
      confirmReset:
        "سيتم إعادة تعيين قاعدة البيانات إلى البيانات الافتراضية. هل أنت متأكد؟",
      confirmComplete: "هل تؤكد أنك أتممت هذا الجزء؟",
      confirmCancel: "هل تريد إلغاء قراءة هذا الجزء؟",
      resetSuccess: "تم إعادة تعيين الجلسة بنجاح! في انتظار مشاركين جدد.",
      resetFailPrefix: "فشل إعادة التعيين: ",
      deleteSuccess: "تم حذف الجلسة بنجاح.",
      deleteFail: "فشل الحذف.",
      leaveSuccess: "لقد غادرت الحلقة.",
      leaveFail: "فشل مغادرة الحلقة.",
      cancelFailed: "فشل الإلغاء.",
      alertStatus: "الحالة: ",
      errorPrefix: "خطأ: ",
      featureFree: "استخدام مجاني",
      featureNoLogin: "الانضمام بدون تسجيل الدخول",
      successLeave: "لقد غادرت الجلسة بنجاح.",
      copyCode: "نسخ الكود",
    },
  },
  fr: {
    common: {
      appTitle: "Spiritual Union for Reflection & Affinity",
      subtitle: "Plateforme de Distribution de Ressources",
      backHome: "Accueil",
      pasteCodeOrLink: "Collez le code ou le lien",
      footerDesc:
        "Plateforme de connexion spirituelle et de distribution de ressources.",
      rightsReserved: "Tous droits réservés.",
      allahAccept: "Qu'Allah l'accepte.",
      loading: "Chargement...",
      close: "Fermer",
      fixedResources: "Ressources fixes",
      resource_YASIN: "Sourate Yasin",
      distributed: "Distribué",
      resource_FETIH: "Sourate Al-Fath",
      resource_CEVSEN: "Jawshan Kabir",
      resource_TEFRICIYE: "Salat al-Tefriciye",
      resource_MUNCIYE: "Salat al-Munciye",
      resource_TEVHIDNAME: "Tawhidname",
      resource_UHUD: "Martyrs de Uhud",
      resource_BEDIR: "Martyrs de Badr",
      resource_SALAVAT: "Salawat",

      sessionCreated: "Rûniştin çêbû",
      cancel: "Annuler",

      copied: "Copié",

      createNewOne: "Créer un nouveau",
      delete: "Supprimer",
      sharedResources: "Ressources partagées",
      successLeave: "Vous avez quitté la session avec succès.",
      copy: "Copier",
      select: "SÉLECTIONNER",
      copyCode: "Copier le code",

      page: "Page",
      part: "Partie",
      person: "Personne",
      total: "Total",
      pieces: "Pièces",
      menuLanguage: "Paramètres de langue",
      default: "Défaut",
      otherResource: "Autre",
      imageMode: "Mode Image",
      continueButton: "CONTINUER",
      adminButton: "Connexion Admin !",
    },
    auth: {
      loginTitle: "Connexion",
      loginButton: "CONNEXION",
      logoutButton: "Déconnexion",
      registerTitle: "Créer un compte",
      registerSubtitle: "Entrez vos détails pour nous rejoindre",
      registerButton: "S'INSCRIRE",
      guestRegister: "S'inscrire",
      guestLogin: "Connexion",
      guestSubtitle: "Plateforme de connexion spirituelle",
      guestMessage:
        "Veuillez vous connecter pour rejoindre des cercles ou créer votre propre distribution.",
      guestNote: "Vous pouvez également rejoindre en tant qu'invité.",
      usernameLabel: "Nom d'utilisateur",
      passwordLabel: "Mot de passe",
      placeholderUser: "Votre nom d'utilisateur",
      placeholderUserExample: "ex: jean123",
      resetsession: "Réinitialiser la session",

      placeholderPass: "******",
      haveAccount: "Vous avez déjà un compte ?",
      noAccount: "Pas de compte ?",
      loginLink: "Connexion",
      targetLabel: "Objectif",
      registerLink: "S'inscrire maintenant",
      loginError: "Nom d'utilisateur ou mot de passe invalide",
      registerSuccess: "Inscription réussie ! Vous pouvez vous connecter.",
      registering: "Inscription en cours...",
      loginRequiredMsg:
        "Vous devez vous connecter pour sélectionner une partie.",
      loginOrRegister: "Connexion ou Inscription",
    },
    landing: {
      landingHeroTitle: "Plateforme d’union spirituelle",
      landingHeroSubtitle:
        "Organisez facilement des khatms du Coran, des cercles de Cevshen et des programmes de dhikr.",
      getStarted: "Commencer",
      featuresTitle1: "Khatms Coran & Cevshen",
      featuresDesc1:
        "Distribuez automatiquement des juz ou des pages. Suivez la progression en direct.",
      featuresTitle2: "Cercles de Dhikr Communs",
      featuresDesc2:
        "Contribuez au pot commun pour les dhikrs comme les Salawats.",
      featuresTitle3: "Lecture Mobile",
      featuresDesc3:
        "Lisez les pages du Coran ou les sections de Cevshen sans quitter l'application.",
      howItWorksTitle: "Comment ça marche ?",
      step1Title: "Créer une session",
      yourTask: "Votre tâche",
      step1Desc: "Sélectionnez la ressource et le nombre de personnes.",
      step2Title: "Inviter",
      step2Desc: "Partagez le code court ou le lien généré.",
      step3Title: "Terminer",
      giveUp: "Abandonner",
      step3Desc: "Chacun lit sa partie, visualisez les progrès instantanément.",
    },
    dashboard: {
      dashboard: "Tableau de bord",
      welcome: "Bienvenue,",
      leaveSession: "Quitter la session",

      dashboardIntro:
        "Que voulez-vous faire dans votre voyage spirituel aujourd'hui ?",
      myCirclesTitle: "Mes Cercles",
      myCreatedTitle: "Mes Distributions",
      joinedSessions: "Cercles rejoints",
      managedSessions: "Cercles gérés",
      createNewSession: "Créer un nouveau cercle",
      noCirclesYet: "Vous n'avez rejoint aucun cercle pour le moment.",
      noCreatedYet: "Vous n'avez pas encore commencé de distribution.",
      noSessionYet: "Pas encore.",
      create: "Créer",
      join: "Rejoindre",
      startReading: "Commencer la lecture",
      trackButton: "Voir l'état",
      backToAdmin: "Retour au tableau de bord",
      adminTitle: "Tableau de bord Admin",
    },
    distribution: {
      createDistTitle: "Démarrer un nouveau cercle",
      createDistDesc:
        "Créez un cercle Coran, Yasin ou Dhikr et partagez le lien.",
      joinDistTitle: "Rejoindre un cercle",
      joinDistDesc: "Entrez le code partagé avec vous pour participer.",
      createButton: "CRÉER",
      joinButton: "Rejoindre",
      enterCode: "Entrez le code de distribution",
      enterCodePlaceholder: "Code de distribution (ex: 12345)",
      guestCheckCode: "Voulez-vous juste vérifier un code ?",
      guestCodePlaceholder: "Entrer le code",
      participantCount: "Nombre de participants ?",
      setTargetCounts: "Définir les objectifs (Optionnel)",
      createDistribution: "CRÉER UNE DISTRIBUTION",
      linkCreated: "Lien créé :",
      copyLink: "Copier le link",
      codeCopied: "Code copié",

      monitorTitle: "Moniteur de Distribution",
      monitorSubtitle: "Entrez un code pour voir qui a pris quoi.",
      distCode: "Code",
      deleteSession: "Effacer la session",
      statusHeader: "Statut",
      assignedTo: "Attribué à",
      resource: "Ressource / Partie",
      progress: "Progrès / Cible",
      occupancy: "OCCUPATION",
      targetLabel: "CIBLE",
      remaining: "Restant",
      distributedResources: "Ressources Partagées",
      individualResources: "Ressources Individuelles",
      creatorLabel: "Créateur",
    },
    reading: {
      readingTitle: "Lecture",
      sessionCodePlaceholder: "Le code existant",
      joinTitle: "Rejoindre le cercle",
      joinIntro: "Veuillez entrer votre nom (Invité)",
      yourName: "Votre Nom",
      takeRead: "PRENDRE",
      readText: "Lire",
      completed: "Terminé",
      finish: "Si vous avez terminé, cliquez",
      selectAndRead: "SÉLECTIONNER & LIRE",
      clickToCount: "CLIQUEZ PENDANT LA LECTURE",
      decrease: "DIMINUER",
      closeWindow: "Fermer la fenêtre",
      chapter: "Chapitre",
      group: "Groupe",
      translationTitle: "Traduction",
      translationPending: "Traduction en attente...",
      arabicPage: "Page Arabe",
      meaningPage: "Page de Sens",
      tabArabic: "Arabe",
      tabLatin: "Transcription",
      tabMeaning: "Traduction",
      homeVerseContent:
        "Sachez que les cœurs ne trouvent la paix que dans le rappel d’Allah.",

      previous: "Précédent",
      next: "Suivant",
      statusEmpty: "DISPONIBLE",
      featureFree: "Utilisation gratuite",
      featureNoLogin: "Participation sans inscription",
      statusTaken: "PRIS",
      full: "PRIS",
      participantName: "Nom du participant",
      cancelRead: "Annuler la lecture",
    },
    alerts: {
      successReset: "Réinitialisation réussie !",
      successDelete: "Supprimé !",
      errorOccurred: "Une erreur est survenue.",
      unexpectedError: "Une erreur inattendue est survenue.",
      connectionError: "Erreur de connexion.",
      errorFetchFailed: "Échec de récupération des données. Code d'erreur :",
      errorInvalidCode: "Erreur : Code invalide ou serveur hors ligne.",
      errorAlreadyTaken:
        "Malheureusement, cette partie a déjà été prise par quelqu'un d'autre.",
      alertSelectResource: "Veuillez sélectionner au moins une ressource.",
      alertEnterName: "Veuillez d'abord entrer votre nom ci-dessus.",
      alertTakenSuccess: "Super ! Vous avez pris cette partie avec succès.",
      confirmDelete: "Êtes-vous sûr de vouloir supprimer cette distribution ?",
      confirmDeleteSession:
        "Êtes-vous sûr de vouloir supprimer cette session définitivement ? Toutes les données seront perdues.",
      confirmLeaveSession:
        "Vous êtes sur le point de quitter ce cercle. Toutes vos tâches seront annulées.",
      confirmResetSession:
        "Êtes-vous sûr de vouloir réinitialiser cette distribution ? Tous les participants seront retirés et les lectures remises à zéro.",
      confirmReset:
        "La base de données sera réinitialisée aux données par défaut. Êtes-vous sûr ?",
      confirmComplete: "Confirmez-vous avoir terminé cette partie ?",
      confirmCancel: "Voulez-vous annuler la lecture de cette partie ?",
      resetSuccess:
        "Session réinitialisée avec succès ! En attente de nouveaux participants.",
      resetFailPrefix: "Échec de la réinitialisation : ",
      deleteSuccess: "Session supprimée avec succès.",
      deleteFail: "Échec de la suppression.",
      leaveSuccess: "Vous avez quitté le cercle.",
      leaveFail: "Échec lors de la tentative de quitter le cercle.",
      cancelFailed: "Annulation échouée.",
      alertStatus: "Statut : ",
      errorPrefix: "Erreur : ",
    },
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("tr");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("appLanguage") as Language;

    if (
      savedLanguage &&
      ["tr", "en", "ku", "ar", "fr"].includes(savedLanguage)
    ) {
      if (savedLanguage !== language) {
        setLanguageState(savedLanguage);
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("appLanguage", lang);
  };

  const t = (key: string): string => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const langData = (translations as any)[language];

    if (key.includes(".")) {
      const keys = key.split(".");
      let value = langData;
      for (const k of keys) {
        if (value && value[k]) {
          value = value[k];
        } else {
          return key;
        }
      }
      return value as string;
    }

    for (const category in langData) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const value = (langData as any)[category]?.[key];
      if (value && typeof value === "string") {
        return value;
      }
    }

    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
